codecov:
    bot: "codecov-io"
    require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        # Project must always have at least 78% coverage (by line)
        target: 20%
        # Whole-project test coverage is allowed to drop up to 1%. (For situtations where we delete code with full coverage)
        threshold: 1%
    patch:
      default:
        # Changes must have at least 100% test coverage (by line)
        target: 100%
